#BeginMacro(qshock)
{{qshock}}
#EndMacro

#BeginMacro(long)
{{long}}
#EndMacro

#BeginMacro(q)
{{q}}
#EndMacro

#BeginMacro(delta)
{{delta}}
#EndMacro

#BeginMacro(k)
{{k}}
#EndMacro

#BeginMacro(inicia)
zz
#EndMacro

#BeginMacro(mirar_arriba)
(0,0,1)=(-1,0,1) and (0,0,1)!=(-2,0,1) and (0,0,1)!=(0,-1,1) and (0,0,1)!=(0,1,1) and (0,0,1)!=(1,0,1)
#EndMacro

#BeginMacro(mirar_abajo)
(0,0,1)=(1,0,1)  and (0,0,1)!=(2,0,1) and (0,0,1)!=(0,-1,1) and (0,0,1)!=(0,1,1) and (0,0,1)!=(-1,0,1)
#EndMacro

#BeginMacro(mirar_derecha)
(0,0,1)=(0,1,1)  and (0,0,1)!=(0,2,1) and (0,0,1)!=(-1,0,1) and (0,0,1)!=(1,0,1) and (0,0,1)!=(0,-1,1)
#EndMacro

#BeginMacro(mirar_izquierda)
(0,0,1)=(0,-1,1)  and (0,0,1)!=(0,-2,1) and (0,0,1)!=(-1,0,1) and (0,0,1)!=(1,0,1) and (0,0,1)!=(0,1,1)
#EndMacro
